[build]
  command = "npm install && npm run generate"
  publish = "dist"
  [build.environment]
    NODE_VERSION = "20"
    NODE_OPTIONS = "--max-old-space-size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[build.processing]
  skip_processing = true 